language: node_js
node_js:
- node
- '4'
- '6.2'
- '6.3'
before_install:
- npm install publish-please
before_script:
- npm prune
- rm -rf ./coverage
script:
- npm test
notifications:
  slack:
    secure: kcn6Ipz/jPcmkJeLRBoddpEOBJO4C+ciQoQLMze5mMhO7I+Uq5xRJuKLotsrtsytCv7zVk8XP2kbyWWqoexX/BdYh9WhmCBKda6lyef/SAGPzd0zmAqbKFKdwmCFIRXrbRhDirJG+kqbUV19BQy28y34lDMev7RyqQQakQLca6Lqf0pPPFrwPSLqmNmUemyigDtkmGGz6ACRrhtBWEdzf9lyVzPX7bnTsrsFT3ImKQr/U9YIGytpEatW80NlmbBYCdnukljB+qrMT2Kz1gjpwJtqPCN8md4UQUxjTsKf+gd5aoUGC9VLzIMMpcz5u7fAmox8DcRA9KftvYYtO2d6ChOJGJPxT+QLv9/GC6ZJkPYfdkFM4xGE2jKaPzJZDksrKD9qarXjwjqriv7m634vnovXQdmwZK6dz4SNT+sHX2z5fNnMjwirIOnNJJg5Ju9VKDRK7wfgW1Xj4H2KW6iWOogp1BzdqVMAgYZGEm5zQuaO1JmSHNXUbK+Afonyv8rHZFgAKeHiS4C1NKqhqG2w1RVjdCfbx7TTnp0hvlUs1uUuHlnlhDHtPq6UU70EB+VqWFOCmSRPj19hQzsd3rMIyhgxvrJ/fJASJQnRDseN+/cx/zwMyg+oc34NhB9DRMIC3MR9uGYLbLW+0j0YrS8IVA5+gl/xjvM6Q8+8ytosDH0=
